backend:
  name: git-gateway
  branch: master
media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "projects"
    label: "Project"
    folder: "_posts/projects"
    create: true
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Order", name: "order", widget: "number"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Logo", name: "logo", widget: "image"}
      - {label: "GPlay Link", name: "gplay", widget: "string", required: false}
      - {label: "AStore Link", name: "astore", widget: "string", required: false}
      - {label: "Website Link", name: "website", widget: "string", required: false}
      - {label: Tags (Comma separated), name: tags, widget: string}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "pages"
    label: "Pages"
    files:
      - label: "About"
        name: "about"
        file: "_site/content/about.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Path, name: path, widget: string}
          - {label: Tags (Comma separated), name: tags, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: "Body", name: "body", widget: "markdown"}
      - label: "Kontakt"
        name: "kontakt"
        file: "_site/content/kontakt.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Path, name: path, widget: string}
          - {label: "Body", name: "body", widget: "markdown"}